name: 'Diff and Status Checker'
description:
  'A GitHub action to check if there are any differences in the current branch
  since the last success check'
author: 'Ricky Shi <ricky.shiyouping@gmail.com>'

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false

outputs:
  hasDiff:
    description:
      'Indicate if there are any differences in the current branch since the
      last success check'

runs:
  using: node16
  main: dist/index.js
