name: 'Diff and Status Checker for Pull Request'
description:
  'A GitHub action to check if there are any differences in the pull request
  since last passed checks'
author: 'Ricky Shi <ricky.shiyouping@gmail.com>'

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
  filters:
    description:
      'Filters applied to changed files and must be separated in a new line.'
    required: false

outputs:
  hasDiff:
    description:
      'Indicate if there are any differences in the current branch since the
      last success check'

runs:
  using: node20
  main: dist/index.js
