name: 'Diff and Status Checker for Pull Request'
description:
  'A GitHub action to check if there are any differences in the pull request
  since last passed checks'
author: 'Ricky Shi <ricky.shiyouping@gmail.com>'
branding:
  color: 'blue'
  icon: 'check-square'
inputs:
  token:
    description:
      'Optional. Default: ${{ github.token }}
      The GitHub token used to create an authenticated client.'
    default: ${{ github.token }}
    required: false
  filters:
    description:
      'Optional.
      A list of filters delimited by comma or in a new line. If specified,
      only changed files in the designated paths will be checked; otherwise
      all will be checked. See https://github.com/micromatch/picomatch
      for how to write glob patterns for your paths.'
    required: false
  includeJobs:
    description:
      'Optional.
      A list of GitHub workflow job names delimited by comma or in a new line.
      If specified, only those jobs in the list will be checked; otherwise all
      will be checked. Only one of `includeJobs` and `excludeJobs` is allowed.

      Note that if a commit has no workflow jobs specified in this list, it will
      be seen as `FAILED`, and the action will continue to check its previous commits.'
    required: false
  excludeJobs:
    description:
      'Optional.
      A list of GitHub workflow job names delimited by comma or in a new line. If
      specified, those jobs in the list will be skipped; otherwise none will be
      skipped. Only one of `includeJobs` and `excludeJobs` is allowed.

      Note that if a commit workflow jobs are all covered by this list, it will be
      seen as `PASSED`, and the action will use the SHA of this commit to calculate
      the Git difference.'
    required: false

outputs:
  hasDiff:
    description:
      'Indicate if there are any differences in the current branch since the
      last success check'

runs:
  using: node20
  main: dist/index.js
