name: Action Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: Action Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.hasDiff }}"
