name: Experiment

on:
  pull_request:
    branches:
      - main

env:
  NAME: prod

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      job1_result: ${{ steps.print.outputs.result}}

    steps:
      - name: Echo
        run: echo "Hello, world!"

      - name: Conditional
        id: conditional
        if: env.NAME == 'true'
        run: echo "Running in dev environment"

      - name: Check
        run: |
          echo ${{ toJson(steps.conditional.conclusion) }}
          echo ${{ toJson(steps.conditional.outcome) }}

      - name: Print
        if: success()
        id: print
        run: echo "result=true" >> "$GITHUB_ENV"


  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Print job 1
        run: |
          echo ${{ toJson(needs.job1.outputs.job1_result) }}
          echo ${{ env }}
