name: Experiment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NAME: prod

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.my_step.outputs.my_value }}
    steps:
    - id: my_step
      run: echo "my_value=Hello World" >> "$GITHUB_ENV"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: print
        run: |
          echo "The output from job1 is: ${{ needs.job1.outputs.my_output }}"
